### ISSUE TITLE
Not able to import sparkdl in jupyter notebook

### ISSUE THREAD

**Issue by yashwanthmadaka24** [databricks/spark-deep-learning#185]
Hi,

I am trying to use this library in jupyter notebook, but I am getting error "no module found".

When I am running the below command 
`pyspark --packages databricks:spark-deep-learning:1.5.0-spark2.4-s_2.11`
I am able to import sparkdl in the spark shell. 

How can I use it in jupyter notebook?

**Comment by zhujiesheng** [comment]
I also have this problem.

**Comment by yashwanthmadaka24** [comment]
Turns out we cannot use it in jupyter notebook. We need to use Azure Databricks to use that module in jupyter notebook.

**Comment by iphton** [comment]
We can import `sparkdl` in jupyter notebook. Yes, if we use `pyspark --packages databricks:spark-deep-learning:1.5.0-spark2.4-s_2.11` this then we no need to worry about some necessary deep learning pipeline packages. And we need to have a net connection though. 

However, we can also make things all in local. Check this [gist](https://gist.github.com/iphton/b0ab252c954eb2a28a984774e3ee1f2d), hope it might help. Cheers.

**Comment by skeller88** [comment]
@innat the gist results in a 404. Can you update?

**Comment by spark-water** [comment]
I found a solution from stack overflow (https://stackoverflow.com/questions/55377712/not-able-to-import-sparkdl-in-jupyter-notebook)

instead of using --packages, just use the .config and 'spark.jars.packages' alias within Jupyter Notebook when initiate a spark session. This would download all dependencies from databricks. You can change version to any release that suits your environment 
spark = (SparkSession
            .builder
            .config('spark.jars.packages', 'databricks:spark-deep-learning:1.5.0-spark2.4-s_2.11')
            .getOrCreate()
)

note that this is very difficult to do with local .jar because none of the releases or current github project has parent dependencies built in. I guess databricks want you to use their package, preferably even with Azure, to run sparkdl. 

Hope it helps others.

**Comment by shekharmayank** [comment]
Same issue I'm facing.

**Comment by innat** [comment]
> @innat the gist results in a 404. Can you update?

@skeller88 
Sorry for being too late, didn't encounter the mail update until now. :(

Update [link](https://gist.github.com/innat/b0ab252c954eb2a28a984774e3ee1f2d), Deep-Learning-Pipelines in Linux based OS.
