### ISSUE TITLE
Scala API

### ISSUE THREAD

**Issue by andresmasegosa** [databricks/spark-deep-learning#36]
Hi, 

what about the Scala API? Any ETA?

**Comment by sueann** [comment]
I think Scala API for image loading, converting, and DeepImageFeaturizer/DeepImagePredictor would make sense since their usage does not require any tf/keras code. Is that what you were thinking?

Let's continue the discussion in https://github.com/databricks/spark-deep-learning/issues/17 - will close this one in favor.
